import Navbar from '@/components/navbar'
import Topbar from '@/components/topbar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-gray-600 grid grid-rows-nav top-0 z-50'>
        <Topbar />
        <div className='h-full relative'>
          <Navbar />
        </div>
      </div>

    </>
  )
}
